app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views as core_views
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    url(r'^$', get_form, name='get_form'),
    url(r'^login/$', core_views.login_view, name='login'),
    url(r'^logout/$', core_views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^get_csv/$', core_views.get_csv, name='get_csv'),
    url(r'^get_pdf/$', core_views.get_pdf, name='get_pdf'),
    url(r'^admin-get-pdf/$', core_views.get_pdf_admin, name="get_pdf_admin"),
    url(r'^paytm-get-response-info/$', core_views.get_paytm_response, name="get_paytm_response"),
   url(r'^paytm-get-response-info$', core_views.get_paytm_response, name="get_paytm_response_NO_slash")

]

for x in FORM_MODELS:
    urlpatterns.append(
        url(r'^'+x[0]+'/$', core_views.form_page, {'url': x[0]})
    )

appform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^application/admin/', admin.site.urls),
    url(r'^application/', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import os
import uuid

from django.db import models
from django.core.validators import RegexValidator, MaxValueValidator, MinValueValidator
from django_countries.fields import CountryField

# Create your models here.
GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)

PROGRAM_CHOICES = (
    ('btech', 'B.Tech.'),
    ('mtech', 'M.Tech.'),
    ('phd', 'Ph.D'),
    ('mba', 'M.B.A')
)

DEPARTMENT_CHOICES = (
    ('B_BT', 'Bio-Technology'),
    ('B_COE', 'Computer Engineering'),
    ('B_CE', 'Civil Engineering'),
    ('B_ECE', 'Electronics and Communication Engineering'),
    ('B_EE', 'Electrical Engineering'),
    ('B_IT', 'Information Technology'),
    ('B_ME', 'Mechanical Engineering'),
    ('B_PIE', 'Production and Industrial Engineering'),
    ('B_ENE', 'Environmental Engineering'),
    ('B_PCT', 'Polymer Science and Chemical Technology'),
    ('B_SE', 'Software Engineering'),
    ('B_EEE', 'Electrical and Electronics Engineering'),
    ('B_MAM', 'Mechanical Engineering with specialization in Automotive'),
    ('B_EP', 'Engineering Physics'),
    ('B_MC', 'Mathematics and Computing'),
    ('M_PTE', 'Polymer Technology'),
    ('M_NST', 'Nano Science and Technology'),
    ('M_NSE', 'Nuclear Science and Engineering'),
    ('M_BIO', 'Bioinformatics'),
    ('M_BME', 'Bio Medical Engineering'),
    ('M_IBT', 'Industrial Bio Training'),
    ('M_GTE', 'Geaotechnical Engineering'),
    ('M_HRE', 'Hydraulics and Water Resource Engineering'),
    ('M_STE', 'Structural Engineering'),
    ('M_CSE', 'Computer Science and Engineering'),
    ('M_SWE', 'Software Engineering'),
    ('M_ISY', 'Information System'),
    ('M_MOCE', 'Microwave and Optical Communication'),
    ('M_SPD', 'Signal Processing and Digital Design'),
    ('M_VLS', 'VLSI Design and Embedded System'),
    ('M_CAI', 'Control and Instrumentation'),
    ('M_PSY', 'Power System'),
    ('M_ENE', 'Environmental Engineering'),
    ('M_CDN', 'Computational Design'),
    ('M_PIE', 'Production Engineering'),
    ('M_RET', 'Renewable Energy Technology'),
    ('M_THE', 'Thermal Engineering')
)

ETHNIC_CHOICES = (
    ('hispanic', 'Hispanic'),
    ('white', 'White'),
    ('black', 'Black'),
    ('asian', 'Asian (Non-Indian)'),
    ('africa_american', 'African American'),
    ('african', 'African'),
    ('alaska', 'Alaska Native'),
    ('asian_indian', 'Asian Indian'),
    ('hawaaiian', 'Native Hawaaiian'),
    ('pascific', 'Other Pascific Islander')
)
PHONE_REGEX = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))


def get_file_name(filename, folder):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/'+folder, filename)


def get_file_path_english_docs(instance, filename):
    return get_file_name(filename, 'english_docs')


def get_file_path_marksheets(instance, filename):
    return get_file_name(filename, 'marksheets')


def get_file_path_sponsor(instance , filename):
    return get_file_name(filename, 'sponsor')


def get_file_path_scholarship(instance, filename):
    return get_file_name(filename, 'scholarship')


def get_file_path_signature(instance, filename):
    return get_file_name(filename, 'signature')


def get_file_path_pic(instance, filename):
    return get_file_name(filename, 'pic')


def get_file_path_recommendation(instance, filename):
    return get_file_name(filename, 'recommendation')


def get_file_path_published_papers(instance, filename):
    return get_file_name(filename, 'published_papers')


class BaseModel(models.Model):
    username = models.CharField(max_length=50, null=False, unique=True)


class BasicInfo(models.Model):
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name =  models.CharField(max_length=50)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
    parent_first_name = models.CharField(max_length=50)
    parent_middle_name = models.CharField(max_length=50, null=True, blank=True)
    parent_last_name =  models.CharField(max_length=50)
    country_of_citizenship = CountryField()
    country_of_birth = CountryField()
    ethnic_group = models.CharField(max_length=20, choices=ETHNIC_CHOICES)
    phone_number = models.CharField(validators=[PHONE_REGEX], max_length=15) # validators should be a list
    email = models.EmailField()
    permanent_address = models.TextField()
    current_address = models.TextField()
    username = models.CharField(max_length=50, null=False, unique=True)
    user_pic = models.ImageField(upload_to=get_file_path_pic)


class PassportInfo(models.Model):
    passport_number = models.CharField(max_length=10)
    place_of_issue = models.CharField(max_length=20)
    issuing_authority = models.CharField(max_length=20)
    date_of_issue = models.DateField(auto_now=False, auto_now_add=False)
    passport_expiry_date = models.DateField(auto_now=False, auto_now_add=False)
    username = models.CharField(max_length=50, null=False, unique=True)


class VisaInfo(models.Model):
    applied_for_indian_visa = models.BooleanField(default=False, choices=BOOL_CHOICES)
    visa_type = models.CharField(max_length=20, null=True, blank=True)
    visa_expiry_date = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    immigration_office = models.CharField(max_length=20, null=True, blank=True)
    refused_entry = models.BooleanField(default=False, choices=BOOL_CHOICES)
    username = models.CharField(max_length=50, null=False, unique=True)


class ApplicationInfo(models.Model):
    program_applying_for = models.CharField(max_length=5, choices=PROGRAM_CHOICES)
    department_preference_1 = models.CharField(max_length=6, choices=DEPARTMENT_CHOICES, null=True, blank=True)
    department_preference_2 = models.CharField(max_length=6, choices=DEPARTMENT_CHOICES, null=True, blank=True)
    department_preference_3 = models.CharField(max_length=6, choices=DEPARTMENT_CHOICES, null=True, blank=True)
    department_preference_4 = models.CharField(max_length=6, choices=DEPARTMENT_CHOICES, null=True, blank=True)
    phd_interest = models.CharField(max_length=50, null=True, blank=True)
    published_papers = models.FileField(upload_to=get_file_path_published_papers, null=True, blank=True)
    username = models.CharField(max_length=50, null=False, unique=True)


class LanguageProficiency(models.Model):
    username = models.CharField(max_length=50, null=False, unique=True)
    proficient_english = models.BooleanField(default=False, choices=BOOL_CHOICES)
    english_document = models.FileField(upload_to=get_file_path_english_docs, null=True, blank=True)
    toefl_choice = models.BooleanField(default=False, choices=BOOL_CHOICES)
    toefl_score = models.IntegerField(validators=[MaxValueValidator(120), MinValueValidator(0)], null=True, blank=True)
    ielts_choice = models.BooleanField(default=False, choices=BOOL_CHOICES)
    ielts_score = models.IntegerField(validators=[MaxValueValidator(9), MinValueValidator(0)], null=True, blank=True)
    other_languages_known = models.CharField(max_length=200, null=True, blank=True)


class AcademicQualification(models.Model):
    degree1 = models.CharField(max_length=20)
    institution1 = models.CharField(max_length=100)
    institution_address1 = models.CharField(max_length=100)
    cgpa_percentage1 = models.CharField(max_length=5)
    marksheet1 = models.FileField(upload_to=get_file_path_marksheets)

    degree2 = models.CharField(max_length=20, null=True, blank=True)
    institution2 = models.CharField(max_length=100, null=True, blank=True)
    institution_address2 = models.CharField(max_length=100, null=True, blank=True)
    cgpa_percentage2 = models.CharField(max_length=5, null=True, blank=True)
    marksheet2 = models.FileField(upload_to=get_file_path_marksheets, null=True, blank=True)

    degree3 = models.CharField(max_length=20, null=True, blank=True)
    institution3 = models.CharField(max_length=100, null=True, blank=True)
    institution_address3 = models.CharField(max_length=100, null=True, blank=True)
    cgpa_percentage3 = models.CharField(max_length=5, null=True, blank=True)
    marksheet3 = models.FileField(upload_to=get_file_path_marksheets, null=True, blank=True)

    degree4 = models.CharField(max_length=20, null=True, blank=True)
    institution4 = models.CharField(max_length=100, null=True, blank=True)
    institution_address4 = models.CharField(max_length=100, null=True, blank=True)
    cgpa_percentage4 = models.CharField(max_length=5, null=True, blank=True)
    marksheet4 = models.FileField(upload_to=get_file_path_marksheets, null=True, blank=True)

    attached_documents_declaration = models.BooleanField(default=False)
    attested_copies_marksheets = models.BooleanField(default=False)
    name_attestation_officer = models.CharField(max_length=150)
    rank_attestation_officer = models.CharField(max_length=50)

    username = models.CharField(max_length=50, null=False, unique=True)


class WorkExperience(models.Model):
    company_name1 = models.CharField(max_length=150, null=True, blank=True)
    company_address1 = models.CharField(max_length=250, null=True, blank=True)
    company_position1 = models.CharField(max_length=100, null=True, blank=True)
    employment_period1 = models.IntegerField(validators=[MinValueValidator(1)], null=True, blank=True)   # in months

    company_name2 = models.CharField(max_length=150, null=True, blank=True)
    company_address2 = models.CharField(max_length=250, null=True, blank=True)

app/templates/forms/acad-info.html
{% extends 'basic_form.html' %}

{% block content %}
<h4>User : {{request.user.username}}
<span style="float: right;"><a href="/application/logout">Logout</a></span>
</h4>
<h3>Academic Information</h3>
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <div class="row">
        <div class="col-sm-2 col-xs-2">Degree</div>
        <div class="col-sm-2 col-xs-2">Institution</div>
        <div class="col-sm-2 col-xs-2">Institution Address</div>
        <div class="col-sm-2 col-xs-2">CGPA Percentage</div>
        <div class="col-sm-2 col-xs-2">Marksheet</div>
        </div>


    {% for field in form %}
        {% if 'Degree' in field.label_tag %}
            <div class="row">
        {% endif %}
                {% if 'Degree' in field.label_tag or 'Institution' in field.label_tag or 'Cgpa' in field.label_tag or 'Marksheet' in field.label_tag %}
        <div class="col-sm-2 col-xs-2">
        {{ field }}
        {% if field.help_text %}
          {%autoescape off %}
            {{ field.help_text }}
          {%endautoescape%}
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
                </div>
                {% if 'Marksheet' in field.label_tag %}
            </div><br>
        {% endif %}
        {% else %}


        <!--Display the attestation details-->
        <div class="row">
        <div class="col-sm-8">
            {{ field.label_tag }}{% if field.field.required %}<strong> *</strong>{% endif %}
            <br>
        {{ field }}
        {% if field.help_text %}
          {%autoescape off %}
            {{ field.help_text }}
          {%endautoescape%}
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
            </div>
        <div class="col-sm-4 col-xs-4"></div>
            </div>

        {% endif %}
    {% endfor %}
        </div>
    <button type="submit">Continue</button>
  </form>
{% endblock content %}

{% block script %}
{{ block.super }}
<script>
    for(var i=1; i<=4; i++){
        $("#id_marksheet"+i).removeClass("form-control")
    }
</script>
{% endblock %}

app/templates/forms/app-info.html
{% extends 'basic_form.html' %}

{% block otherlibs %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" integrity="sha256-iXUYfkbVl5itd4bAkFH5mjMEN5ld9t3OHvXX3IU8UxU=" crossorigin="anonymous" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js" integrity="sha256-egVvxkq6UBCQyKzRBrDHu8miZ5FOaVrjSqQqauKglKc=" crossorigin="anonymous"></script>
{% endblock %}

{% block script %}

    {{ block.super }}

    <script>
    var dept1 = $("#id_department_preference_1")
    var dept2 = $("#id_department_preference_2")
    var dept3 = $("#id_department_preference_3")
    var dept4 = $("#id_department_preference_4")
    var valueSet = new Set();
    hideAll()
    function hideAll() {
        $("select[id^='id_department_preference_']").prop('required', false).parent().hide()
        $("select[id^='id_department_preference_'] option").hide()
        $("select[id^='id_department_preference_'] option:selected").prop("selected", false);
        $("select[id^='id_department_preference_'] option[value='']").prop("selected", true)
        $("#id_phd_interest").prop('required', false).parent().hide()
        $("#id_published_papers").parent().hide()
    }

    function showThese(toShow) {
        if(toShow == 'btech') {
            console.log('show btech')
            $('option[value^="B_"]').show()
            $("select[id^='id_department_preference_'").prop('required', true).parent().show()
        } else if (toShow == 'mtech') {
            $('option[value^="M_"]').show()
            $("select[id^='id_department_preference_'").prop('required', true).parent().show()
        } else if (toShow == 'phd') {
            $("#id_phd_interest").prop('required', true).parent().show()
            $("#id_published_papers").parent().show()
        }
    }
    $("#id_program_applying_for").change(function(){
        console.log($("#id_program_applying_for option:selected").val())
        hideAll()
        showThese($("#id_program_applying_for option:selected").val())
    });
    $("select").change(function(){

        console.log("change occured")
        if(dept1.val() && dept2.val() && dept3.val() && dept4.val()) {
            $(':input[type="submit"]').removeClass('disabled');
            $(':input[type="submit"]').prop('disabled', false);
            valueSet.add(dept1.val())
            valueSet.add(dept2.val())
            valueSet.add(dept3.val())
            valueSet.add(dept4.val())
            if(valueSet.size < 4){
                sweetAlert("Wrong Selection", "Cannot select the same course!", "error");
                $(':input[type="submit"]').addClass('disabled');
                $(':input[type="submit"]').prop('disabled', true)
            }
        }
    })

    </script>

{% endblock %}

app/templates/forms/basic-info.html
{% extends 'basic_form.html' %}


{% block content %}
<h4>User : {{request.user.username}}
<span style="float: right;"><a href="/application/logout">Logout</a></span>
</h4>
<h3> Basic Info </h3>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
    {% for field in form %}
        <div class="container">
        <div class="col-xs-4">
            {{ field.label_tag }}{% if field.field.required %}<strong> *</strong>{% endif %}
            {% if field.name == 'current_address' %}
            <div><label for="address_checkbox" style="word-wrap:break-word"><input id="address_checkbox" type="checkbox" style="vertical-align:left;"/>
                Same as permanent address</label></div>
                {% endif %}
            <br>
        {{ field }}
        {% if field.help_text %}
          {%autoescape off %}
            {{ field.help_text }}
          {%endautoescape%}
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
            </div>
        <div class="col-xs-8"></div>
            </div>
        <br>
    {% endfor %}
        </div>
    <button type="submit">Continue</button>
  </form>
{% endblock content %}

{% block script %}
    {{ block.super }}
    <script>
    swal("You've been sent an email. Check your mailbox.", "Note: If email is not received immediately check after some time");
    $("#address_checkbox").click(function(){
        if(document.getElementById('address_checkbox').checked){
            $("#id_current_address").val($("#id_permanent_address").val());
         }

    })
    $("#id_country_of_citizenship").change(function() {
        console.log($("#id_country_of_citizenship").val())
        jQuery.getJSON("https://restcountries.eu/rest/v2/alpha/"+$("#id_country_of_citizenship").val(), function(data){
            $("#id_phone_number").val("+"+data["callingCodes"][0])
        })
    })
    </script>
{% endblock %}

app/templates/forms/disability-info.html
{% extends 'basic_form.html' %}

<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

{% block subheading %}
<br>
<h3>Do you have any physical or mental health condition or other issue which may prevent you to undertake full-time study?</h3>
<br>
{% endblock %}

app/templates/forms/final-declare.html
{% extends 'basic_form.html' %}

<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

{% block script %}
{{ block.super }}
<script>
    $("#id_signature").removeClass("form-control")
</script>
{% endblock %}

app/templates/forms/guardian-info.html
{% extends 'basic_form.html' %}

<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

{% block script %}
{{ block.super }}
<script>
    $("#id_approval_letter").removeClass("form-control")


    function disable() {
        $("input[type='text']").prop('readonly', true).prop('required', false).val("");
        $("input[type='email']").prop('readonly', true).prop('required', false);
        $("textarea").prop('readonly', true).prop('required', false);
        $( ".datepicker" ).removeClass("hasDatepicker")
        $("#id_visa_expiry_date").datepicker({minDate:-1,maxDate:-2}).prop('readonly', true).prop('required', false);
    }
    disable();
    $("#id_guardian_available_0").click(function() {
        $("input[type='text']").prop('readonly', false).prop('required', true);
        $("input[type='email']").prop('readonly', false).prop('required', true);
        $("textarea").prop('readonly', false).prop('required', true);
        $( ".datepicker" ).removeClass("hasDatepicker")
        $( ".datepicker" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "yy-mm-dd",
            minDate: new Date(2016, 1 - 1, 1),
            maxDate: new Date(2040, 1 - 1, 1),
            yearRange: "-100:+20"
        }).prop('readonly', false).prop('required', true);
    })
    $("#id_guardian_available_1").click(function() {
        disable()
    })
</script>
{% endblock %}

app/templates/forms/lang-info.html
{% extends 'basic_form.html' %}

{% block subheading %}
<h3>Language Proficiency Information</h3>
{% endblock %}
<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

{% block script %}
{{ block.super }}
<script>

    function disable(myElement) {
        $(myElement).prop("disabled", true)
        $(myElement).prop("required", false)
    }

    function enable(myElement) {
        $(myElement).prop("disabled", false)
        $(myElement).prop("required", true)
    }

    disable("#id_english_document")
    disable("#id_toefl_score")
    disable("#id_ielts_score")


    $("#id_proficient_english_0").click(function() {
        enable("#id_english_document")
    })
    $("#id_proficient_english_1").click(function() {
        disable("#id_english_document")
    })

    $("#id_toefl_choice_0").click(function() {
        enable("#id_toefl_score")
    })
    $("#id_toefl_choice_1").click(function() {
        disable("#id_toefl_score")
    })

    $("#id_ielts_choice_0").click(function() {
        enable("#id_ielts_score")
    })
    $("#id_ielts_choice_1").click(function() {
        disable("#id_ielts_score")
    })


</script>
{% endblock %}

app/templates/forms/passport-info.html
{% extends 'basic_form.html' %}

{% block subheading %}
<br>
<h3>Passport Info</h3>
<br>
{% endblock %}
<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

app/templates/forms/recommend-info.html
{% extends 'basic_form.html' %}

{% block content %}
<h4>User : {{request.user.username}}
<span style="float: right;"><a href="/application/logout">Logout</a></span>
</h4>
<form method="post">
    {% csrf_token %}
    <div class="form-group row">
        <div class="row">
            <div class="col-sm-3">Recommendation Name</div>
            <div class="col-sm-3">Recommendation Email</div>
            <div class="col-sm-3">Recommendation Phone</div>
            <div class="col-sm-3">Recommendation Letter</div>
        </div>


    {% for field in form %}
        {% if 'name' in field.label_tag %}
            <div class="row">
        {% endif %}
        <div class="col-sm-3">
        {{ field }}
        {% if field.help_text %}
          {%autoescape off %}
            {{ field.help_text }}
          {%endautoescape%}
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
                </div>
                {% if 'letter' in field.label_tag %}
            </div><br>
        {% endif %}
    {% endfor %}
        </div>
    <button type="submit">Continue</button>
  </form>
{% endblock content %}

{% block script %}
{{ block.super }}
<script>
    for(var i=1; i<=4; i++){
        $("#id_marksheet"+i).removeClass("form-control")
    }
</script>
{% endblock %}

app/templates/forms/scholar-info.html
{% extends 'basic_form.html' %}

<!--<form method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for field in form %}-->
      <!--<p>-->
        <!--{{ field.label_tag }}<br>-->
        <!--{{ field }}-->
        <!--{% if field.help_text %}-->
          <!--{%autoescape off %}-->
            <!--{{ field.help_text }}-->
          <!--{%endautoescape%}-->
        <!--{% endif %}-->
        <!--{% for error in field.errors %}-->
          <!--<p style="color: red">{{ error }}</p>-->
        <!--{% endfor %}-->
      <!--</p>-->
    <!--{% endfor %}-->
    <!--<button type="submit">Continue</button>-->
  <!--</form>-->

{% block script %}
{{ block.super }}
<script>
    $("#id_approval_letter").removeClass("form-control")


    function disable() {
        $("input[type='text']").prop('readonly', true).prop('required', false).val("");
        $("#id_approval_letter").prop('disabled', true).prop('required', false)
        $( ".datepicker" ).removeClass("hasDatepicker")
        $("#id_visa_expiry_date").datepicker({minDate:-1,maxDate:-2}).prop('readonly', true).prop('required', false);
    }
    disable();
    $("#id_scholarship_bool_0").click(function() {
        $("input[type='text']").prop('readonly', false).prop('required', true);
        $("#id_approval_letter").prop('disabled', false).prop('required', true)
        $( ".datepicker" ).removeClass("hasDatepicker")
        $( ".datepicker" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "yy-mm-dd",
            minDate: new Date(2016, 1 - 1, 1),
            maxDate: new Date(2040, 1 - 1, 1),
            yearRange: "-100:+20"
        }).prop('readonly', false).prop('required', true);
    })
    $("#id_applied_for_indian_visa_1").click(function() {
        disable()
    })
</script>
{% endblock %}